version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.18
    working_directory: ~/app

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci

  lint:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check

  test:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run: npm run test

  docker-build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t nksusn/cicd-demo-app:latest .
            docker push nksusn/cicd-demo-app:latest

  healthcheck:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Check deployment health
          command: |
            if [ -n "$DEPLOY_URL" ]; then
              curl -sSf "$DEPLOY_URL/health" || exit 1
              echo "Health check passed for $DEPLOY_URL"
            else
              echo "DEPLOY_URL not set, skipping health check"
            fi

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - lint
      - docker-build-and-push:
          requires:
            - test
      - healthcheck:
          requires:
            - docker-build-and-push
